name: unittest

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  multiplex-unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-html jsonschema

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest -v --html=report.html --self-contained-html multiplex.py tests/*.py

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
